language: erlang
notifications:
  email: yet.another.mqtt.server@gmail.com
otp_release:
  - 18.3
script:
  - rebar3 compile && rebar3 skip_deps=true eunit && dialyzer -r _build/test/lib/yams_mqtt_lib/ebin/